use_frameworks!

platform :ios, '13.0'

target 'AUIKit_Example' do
  pod 'AUIKit', :path => '../'
  pod 'AgoraRtcEngine_iOS', :path => './libs'
#  pod 'LookinServer'
  pod 'AgoraLyricsScore', '1.1.1-beta-3'

  target 'AUIKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
